/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["entries_list"];
        put?: never;
        post: operations["entries_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["entries_retrieve"];
        put: operations["entries_update"];
        post?: never;
        delete: operations["entries_destroy"];
        options?: never;
        head?: never;
        patch: operations["entries_partial_update"];
        trace?: never;
    };
    "/api/goals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["goals_list"];
        put?: never;
        post: operations["goals_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["goals_retrieve"];
        put: operations["goals_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["goals_partial_update"];
        trace?: never;
    };
    "/api/goals/by-person/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["goals_by_person_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["goals_by_person_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CalorieEntry: {
            readonly id: number;
            person_type: components["schemas"]["PersonTypeEnum"];
            title: string;
            description?: string;
            calories: number;
            /** Format: uri */
            image?: string | null;
            readonly image_url: string;
            ingredients?: components["schemas"]["Ingredient"][];
            /** Format: date-time */
            eaten_at?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        DailyCalorieSummary: {
            /** Format: date */
            date: string;
            total_calories: number;
            entry_count: number;
        };
        Ingredient: {
            readonly id: number;
            name: string;
            /** Format: decimal */
            weight_grams?: string | null;
        };
        MonthlyDashboard: {
            person_type: string;
            year: number;
            month: number;
            daily_goal: number;
            monthly_goal: number;
            total_calories: number;
            daily_summaries: components["schemas"]["DailyCalorieSummary"][];
            /** Format: double */
            avg_calories_this_week: number;
            /** Format: double */
            avg_calories_this_month: number;
            /** Format: double */
            avg_calories_this_year: number;
        };
        PatchedCalorieEntry: {
            readonly id?: number;
            person_type?: components["schemas"]["PersonTypeEnum"];
            title?: string;
            description?: string;
            calories?: number;
            /** Format: uri */
            image?: string | null;
            readonly image_url?: string;
            ingredients?: components["schemas"]["Ingredient"][];
            /** Format: date-time */
            eaten_at?: string;
            /** Format: date-time */
            readonly created_at?: string;
        };
        PatchedPersonGoal: {
            readonly id?: number;
            person_type?: components["schemas"]["PersonTypeEnum"];
            daily_goal_calories?: number;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PersonGoal: {
            readonly id: number;
            person_type: components["schemas"]["PersonTypeEnum"];
            daily_goal_calories?: number;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `filip` - Filip
         *     * `klara` - Klara
         * @enum {string}
         */
        PersonTypeEnum: "filip" | "klara";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard_list: {
        parameters: {
            query: {
                month?: number;
                person_type: string;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyDashboard"][];
                };
            };
        };
    };
    entries_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalorieEntry"][];
                };
            };
        };
    };
    entries_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CalorieEntry"];
                "application/x-www-form-urlencoded": components["schemas"]["CalorieEntry"];
                "application/json": components["schemas"]["CalorieEntry"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalorieEntry"];
                };
            };
        };
    };
    entries_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this calorie entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalorieEntry"];
                };
            };
        };
    };
    entries_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this calorie entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CalorieEntry"];
                "application/x-www-form-urlencoded": components["schemas"]["CalorieEntry"];
                "application/json": components["schemas"]["CalorieEntry"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalorieEntry"];
                };
            };
        };
    };
    entries_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this calorie entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    entries_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this calorie entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedCalorieEntry"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCalorieEntry"];
                "application/json": components["schemas"]["PatchedCalorieEntry"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalorieEntry"];
                };
            };
        };
    };
    goals_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"][];
                };
            };
        };
    };
    goals_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["PersonGoal"];
                "multipart/form-data": components["schemas"]["PersonGoal"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"];
                };
            };
        };
    };
    goals_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this person goal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"];
                };
            };
        };
    };
    goals_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this person goal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["PersonGoal"];
                "multipart/form-data": components["schemas"]["PersonGoal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"];
                };
            };
        };
    };
    goals_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this person goal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPersonGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPersonGoal"];
                "multipart/form-data": components["schemas"]["PatchedPersonGoal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"];
                };
            };
        };
    };
    goals_by_person_retrieve: {
        parameters: {
            query: {
                person_type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"];
                };
            };
        };
    };
    goals_by_person_partial_update: {
        parameters: {
            query: {
                person_type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPersonGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPersonGoal"];
                "multipart/form-data": components["schemas"]["PatchedPersonGoal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"];
                };
            };
        };
    };
}
