/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_list"];
        put?: never;
        post: operations["categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_retrieve"];
        put: operations["categories_update"];
        post?: never;
        delete: operations["categories_destroy"];
        options?: never;
        head?: never;
        patch: operations["categories_partial_update"];
        trace?: never;
    };
    "/api/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["entries_list"];
        put?: never;
        post: operations["entries_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["entries_retrieve"];
        put: operations["entries_update"];
        post?: never;
        delete: operations["entries_destroy"];
        options?: never;
        head?: never;
        patch: operations["entries_partial_update"];
        trace?: never;
    };
    "/api/estimate-calories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["estimate_calories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["goals_list"];
        put?: never;
        post: operations["goals_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["goals_retrieve"];
        put: operations["goals_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["goals_partial_update"];
        trace?: never;
    };
    "/api/goals/by-person/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["goals_by_person_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["goals_by_person_partial_update"];
        trace?: never;
    };
    "/api/meal-plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["meal_plans_list"];
        put?: never;
        post: operations["meal_plans_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meal-plans/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["meal_plans_retrieve"];
        put: operations["meal_plans_update"];
        post?: never;
        delete: operations["meal_plans_destroy"];
        options?: never;
        head?: never;
        patch: operations["meal_plans_partial_update"];
        trace?: never;
    };
    "/api/meal-plans/bulk-create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["meal_plans_bulk_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meal-plans/bulk-delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["meal_plans_bulk_delete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meal-plans/mark-processed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["meal_plans_mark_processed_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predefined-meals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["predefined_meals_list"];
        put?: never;
        post: operations["predefined_meals_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predefined-meals/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["predefined_meals_retrieve"];
        put: operations["predefined_meals_update"];
        post?: never;
        delete: operations["predefined_meals_destroy"];
        options?: never;
        head?: never;
        patch: operations["predefined_meals_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CalorieEntry: {
            readonly id: number;
            person_type: components["schemas"]["PersonTypeEnum"];
            /** @default  */
            title: string;
            description?: string;
            /** @default 0 */
            calories: number;
            /** Format: uri */
            image?: string | null;
            readonly image_url: string;
            ingredients?: components["schemas"]["Ingredient"][];
            /** Format: date-time */
            eaten_at?: string;
            /** Format: date-time */
            readonly created_at: string;
            predefined_meal?: number | null;
            readonly predefined_meal_id: number | null;
        };
        Category: {
            readonly id: number;
            name: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly meals: components["schemas"]["PredefinedMeal"][];
        };
        DailyCalorieSummary: {
            /** Format: date */
            date: string;
            total_calories: number;
            entry_count: number;
        };
        EstimateCaloriesIngredient: {
            name: string;
            weight_grams?: number | null;
        };
        EstimateCaloriesRequest: {
            /** @default  */
            title: string;
            /** @default  */
            description: string;
            ingredients: components["schemas"]["EstimateCaloriesIngredient"][];
        };
        EstimateCaloriesResponse: {
            estimated_calories: number;
        };
        Ingredient: {
            readonly id: number;
            name: string;
            /** Format: decimal */
            weight_grams?: string | null;
        };
        MealPlan: {
            readonly id: number;
            person_type: components["schemas"]["PersonTypeEnum"];
            /** Format: date */
            date: string;
            predefined_meal: number;
            readonly predefined_meal_name: string;
            readonly predefined_meal_calories: number;
            readonly is_processed: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        MonthlyDashboard: {
            person_type: string;
            year: number;
            month: number;
            daily_goal: number;
            monthly_goal: number;
            total_calories: number;
            daily_summaries: components["schemas"]["DailyCalorieSummary"][];
            /** Format: double */
            avg_calories_this_week: number;
            /** Format: double */
            avg_calories_this_month: number;
            /** Format: double */
            avg_calories_this_year: number;
        };
        PatchedCalorieEntry: {
            readonly id?: number;
            person_type?: components["schemas"]["PersonTypeEnum"];
            /** @default  */
            title: string;
            description?: string;
            /** @default 0 */
            calories: number;
            /** Format: uri */
            image?: string | null;
            readonly image_url?: string;
            ingredients?: components["schemas"]["Ingredient"][];
            /** Format: date-time */
            eaten_at?: string;
            /** Format: date-time */
            readonly created_at?: string;
            predefined_meal?: number | null;
            readonly predefined_meal_id?: number | null;
        };
        PatchedCategory: {
            readonly id?: number;
            name?: string;
            /** Format: date-time */
            readonly created_at?: string;
            readonly meals?: components["schemas"]["PredefinedMeal"][];
        };
        PatchedMealPlan: {
            readonly id?: number;
            person_type?: components["schemas"]["PersonTypeEnum"];
            /** Format: date */
            date?: string;
            predefined_meal?: number;
            readonly predefined_meal_name?: string;
            readonly predefined_meal_calories?: number;
            readonly is_processed?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
        };
        PatchedPersonGoal: {
            readonly id?: number;
            person_type?: components["schemas"]["PersonTypeEnum"];
            daily_goal_calories?: number;
            auto_add_meal_plan?: boolean;
            estimation_notes?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedPredefinedMeal: {
            readonly id?: number;
            name?: string;
            calories?: number;
            category?: number;
            /** Format: date-time */
            readonly created_at?: string;
            ingredients?: components["schemas"]["PredefinedMealIngredient"][];
        };
        PersonGoal: {
            readonly id: number;
            person_type: components["schemas"]["PersonTypeEnum"];
            daily_goal_calories?: number;
            auto_add_meal_plan?: boolean;
            estimation_notes?: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `filip` - Filip
         *     * `klara` - Klara
         * @enum {string}
         */
        PersonTypeEnum: "filip" | "klara";
        PredefinedMeal: {
            readonly id: number;
            name: string;
            calories: number;
            category: number;
            /** Format: date-time */
            readonly created_at: string;
            ingredients?: components["schemas"]["PredefinedMealIngredient"][];
        };
        PredefinedMealIngredient: {
            readonly id: number;
            name: string;
            /** Format: decimal */
            weight_grams?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
                "application/x-www-form-urlencoded": components["schemas"]["Category"];
                "multipart/form-data": components["schemas"]["Category"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
                "application/x-www-form-urlencoded": components["schemas"]["Category"];
                "multipart/form-data": components["schemas"]["Category"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCategory"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCategory"];
                "multipart/form-data": components["schemas"]["PatchedCategory"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    dashboard_list: {
        parameters: {
            query: {
                month?: number;
                person_type: string;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyDashboard"][];
                };
            };
        };
    };
    entries_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalorieEntry"][];
                };
            };
        };
    };
    entries_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CalorieEntry"];
                "application/x-www-form-urlencoded": components["schemas"]["CalorieEntry"];
                "application/json": components["schemas"]["CalorieEntry"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalorieEntry"];
                };
            };
        };
    };
    entries_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this calorie entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalorieEntry"];
                };
            };
        };
    };
    entries_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this calorie entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CalorieEntry"];
                "application/x-www-form-urlencoded": components["schemas"]["CalorieEntry"];
                "application/json": components["schemas"]["CalorieEntry"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalorieEntry"];
                };
            };
        };
    };
    entries_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this calorie entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    entries_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this calorie entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedCalorieEntry"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCalorieEntry"];
                "application/json": components["schemas"]["PatchedCalorieEntry"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalorieEntry"];
                };
            };
        };
    };
    estimate_calories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstimateCaloriesRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateCaloriesResponse"];
                };
            };
        };
    };
    goals_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"][];
                };
            };
        };
    };
    goals_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["PersonGoal"];
                "multipart/form-data": components["schemas"]["PersonGoal"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"];
                };
            };
        };
    };
    goals_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this person goal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"];
                };
            };
        };
    };
    goals_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this person goal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["PersonGoal"];
                "multipart/form-data": components["schemas"]["PersonGoal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"];
                };
            };
        };
    };
    goals_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this person goal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPersonGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPersonGoal"];
                "multipart/form-data": components["schemas"]["PatchedPersonGoal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"];
                };
            };
        };
    };
    goals_by_person_retrieve: {
        parameters: {
            query: {
                person_type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"];
                };
            };
        };
    };
    goals_by_person_partial_update: {
        parameters: {
            query: {
                person_type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPersonGoal"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPersonGoal"];
                "multipart/form-data": components["schemas"]["PatchedPersonGoal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonGoal"];
                };
            };
        };
    };
    meal_plans_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlan"][];
                };
            };
        };
    };
    meal_plans_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealPlan"];
                "application/x-www-form-urlencoded": components["schemas"]["MealPlan"];
                "multipart/form-data": components["schemas"]["MealPlan"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlan"];
                };
            };
        };
    };
    meal_plans_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this meal plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlan"];
                };
            };
        };
    };
    meal_plans_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this meal plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealPlan"];
                "application/x-www-form-urlencoded": components["schemas"]["MealPlan"];
                "multipart/form-data": components["schemas"]["MealPlan"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlan"];
                };
            };
        };
    };
    meal_plans_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this meal plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    meal_plans_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this meal plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMealPlan"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMealPlan"];
                "multipart/form-data": components["schemas"]["PatchedMealPlan"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlan"];
                };
            };
        };
    };
    meal_plans_bulk_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealPlan"];
                "application/x-www-form-urlencoded": components["schemas"]["MealPlan"];
                "multipart/form-data": components["schemas"]["MealPlan"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlan"];
                };
            };
        };
    };
    meal_plans_bulk_delete_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealPlan"];
                "application/x-www-form-urlencoded": components["schemas"]["MealPlan"];
                "multipart/form-data": components["schemas"]["MealPlan"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlan"];
                };
            };
        };
    };
    meal_plans_mark_processed_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealPlan"];
                "application/x-www-form-urlencoded": components["schemas"]["MealPlan"];
                "multipart/form-data": components["schemas"]["MealPlan"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlan"];
                };
            };
        };
    };
    predefined_meals_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredefinedMeal"][];
                };
            };
        };
    };
    predefined_meals_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredefinedMeal"];
                "application/x-www-form-urlencoded": components["schemas"]["PredefinedMeal"];
                "multipart/form-data": components["schemas"]["PredefinedMeal"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredefinedMeal"];
                };
            };
        };
    };
    predefined_meals_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this predefined meal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredefinedMeal"];
                };
            };
        };
    };
    predefined_meals_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this predefined meal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredefinedMeal"];
                "application/x-www-form-urlencoded": components["schemas"]["PredefinedMeal"];
                "multipart/form-data": components["schemas"]["PredefinedMeal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredefinedMeal"];
                };
            };
        };
    };
    predefined_meals_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this predefined meal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    predefined_meals_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this predefined meal. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPredefinedMeal"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPredefinedMeal"];
                "multipart/form-data": components["schemas"]["PatchedPredefinedMeal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredefinedMeal"];
                };
            };
        };
    };
}
