# Generated by Django 5.2.5 on 2026-02-17 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('filip', 'Filip'), ('klara', 'Klara')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('calories', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='entries/%Y/%m/')),
                ('eaten_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'calorie_entry',
                'ordering': ['-eaten_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('filip', 'Filip'), ('klara', 'Klara')], max_length=10, unique=True)),
                ('daily_goal_calories', models.PositiveIntegerField(default=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'person_goal',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='main.calorieentry')),
            ],
            options={
                'db_table': 'ingredient',
                'ordering': ['id'],
            },
        ),
    ]
