# Generated by Django 5.2.5 on 2026-03-08 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_predefinedmeal_calorieentry_predefined_meal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persongoal',
            name='auto_add_meal_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('filip', 'Filip'), ('klara', 'Klara')], max_length=10)),
                ('date', models.DateField()),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predefined_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='main.predefinedmeal')),
            ],
            options={
                'db_table': 'meal_plan',
                'ordering': ['date', 'id'],
            },
        ),
    ]
