# Generated by Django 5.2.5 on 2026-03-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_persongoal_auto_add_meal_plan_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='persongoal',
            name='estimation_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
